//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPromotionDiscountView
    {
        public int PriceScheduleId { get; set; }
        public string Code { get; set; }
        public decimal Discount { get; set; }
        public decimal FullQty { get; set; }
        public decimal FullPrice { get; set; }
        public int Expr1 { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int FKProduct { get; set; }
        public decimal GetCurrentPrice { get; set; }
    }
}
