//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    
    public partial class fn_GetResultDate_Result1
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string ThaiName { get; set; }
        public Nullable<decimal> qty { get; set; }
    }
}
