//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WH_TRATEntities : DbContext
    {
        public WH_TRATEntities()
            : base("name=WH_TRATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WH_PRODUCT_MAST_DTL_DELETE> WH_PRODUCT_MAST_DTL_DELETE { get; set; }
        public virtual DbSet<WH_PRODUCT_MAST_HD> WH_PRODUCT_MAST_HD { get; set; }
        public virtual DbSet<WH_PRODUCT_MAST_HD_DELETE> WH_PRODUCT_MAST_HD_DELETE { get; set; }
        public virtual DbSet<WH_PRODUCT_MAST_DTL> WH_PRODUCT_MAST_DTL { get; set; }
    }
}
