//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WH_TRATEntities : DbContext
    {
        public WH_TRATEntities()
            : base("name=WH_TRATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WH_LOCSTK> WH_LOCSTK { get; set; }
        public virtual DbSet<WH_PRODUCT_MAST_DTL> WH_PRODUCT_MAST_DTL { get; set; }
        public virtual DbSet<WH_PRODUCT_MAST_HD> WH_PRODUCT_MAST_HD { get; set; }
        public virtual DbSet<PS_PO_ORDER> PS_PO_ORDER { get; set; }
        public virtual DbSet<WH_LOCATION_MAST> WH_LOCATION_MAST { get; set; }
        public virtual DbSet<WH_CUSTOMER_MAST> WH_CUSTOMER_MAST { get; set; }
        public virtual DbSet<WH_BRAND_MAST> WH_BRAND_MAST { get; set; }
    }
}
