//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class PS_PO_ORDER
    {
        public int ROWID { get; set; }
        public int PO_ID { get; set; }
        public string PO_NO { get; set; }
        public int OBJ_ID { get; set; }
        public string OBJ_NAME { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public int USER_ID { get; set; }
        public bool ENABLE { get; set; }
        public Nullable<System.DateTime> CONFIRM_DATE { get; set; }
        public Nullable<System.DateTime> CANCEL_DATE { get; set; }
        public Nullable<int> CONFIRM_USER { get; set; }
        public string RCV_DOC { get; set; }
        public Nullable<System.DateTime> RCV_DATE { get; set; }
        public int VAT_TYPE { get; set; }
        public Nullable<System.DateTime> CONFIRMRCV { get; set; }
    }
}
