//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DifStockCount01
    {
        public int FKProduct { get; set; }
        public Nullable<decimal> BalRemQty { get; set; }
        public Nullable<decimal> CountRemQty { get; set; }
        public Nullable<decimal> DifCount { get; set; }
        public Nullable<decimal> TotalSell { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    }
}
