//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PO
    {
        public Nullable<int> Id { get; set; }
        public string VendorName { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string CreateBy { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> POExpire { get; set; }
        public string PaymentTypeName { get; set; }
        public Nullable<System.DateTime> NotApproveDate { get; set; }
        public string NotApproveBy { get; set; }
        public string NotApproveRemark { get; set; }
        public Nullable<decimal> TotalBalance { get; set; }
        public Nullable<decimal> TotalGift { get; set; }
    }
}
