//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Profit
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string ThaiName { get; set; }
        public string ProductVatTypeName { get; set; }
        public string ProductGroupsName { get; set; }
        public string ProductCategoryName { get; set; }
        public string SupplierName { get; set; }
        public string VendorName { get; set; }
        public string ProductBrandsName { get; set; }
        public string ProductUnitName { get; set; }
        public Nullable<decimal> PackSize { get; set; }
        public Nullable<decimal> CostOnly { get; set; }
        public Nullable<decimal> CostAndVat { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public bool Enable { get; set; }
        public int FKProductGroup { get; set; }
        public int FKProductCategory { get; set; }
        public int FKProductBrand { get; set; }
        public int FKSupplier { get; set; }
        public int FKVender { get; set; }
    }
}
