//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RcvDetail
    {
        public int Id { get; set; }
        public string DocumentNo { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string WHCode { get; set; }
        public string WHName { get; set; }
        public string TypeCode { get; set; }
        public string TypeName { get; set; }
        public string Description { get; set; }
        public int FKProductDetail { get; set; }
        public string ProductDetailCode { get; set; }
        public string ProductName { get; set; }
        public string ProductDetailName { get; set; }
        public string Unit { get; set; }
        public decimal PackSize { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime ProductDate { get; set; }
        public Nullable<int> FKLocation { get; set; }
        public string Location { get; set; }
        public Nullable<int> PalletNo { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
    }
}
