//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StockCard
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsPlus { get; set; }
        public string TransactionTypeName { get; set; }
        public string ProductsName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> PackSize { get; set; }
        public decimal CurrentQty { get; set; }
        public decimal ActionQty { get; set; }
        public decimal ActionQtyUnit { get; set; }
        public bool Enable { get; set; }
        public int IdTransactionType { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public int FKProductDetails { get; set; }
    }
}
