//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_StockBal01
    {
        public bool Enable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int FKProduct { get; set; }
        public string Barcode { get; set; }
        public string ThaiName { get; set; }
        public string FKProductGroup { get; set; }
        public string FKUnit { get; set; }
        public decimal PackSize { get; set; }
        public int FKTransactionType { get; set; }
        public decimal ActionQty { get; set; }
        public decimal CostOnlyPerUnit { get; set; }
        public decimal SellPricePerUnit { get; set; }
        public Nullable<decimal> RemQty { get; set; }
    }
}
