//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WmsCard
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ProductName { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> PackSize { get; set; }
        public string TransactionWmsName { get; set; }
        public Nullable<bool> IsPlus { get; set; }
        public decimal ActionQty { get; set; }
        public decimal ActionQtyUnit { get; set; }
        public decimal ResultQty { get; set; }
        public decimal ResultQtyUnit { get; set; }
        public string WarehouseName { get; set; }
        public string ZoneName { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> ProductsID { get; set; }
        public int TransactionID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
    }
}
