//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CheckFront_01_11_17_BCK
    {
        public string DateCreateStr { get; set; }
        public string DocNo { get; set; }
        public int Number { get; set; }
        public decimal QtyUnit1 { get; set; }
        public decimal QtyUnit2 { get; set; }
        public decimal SellPricePerUnit { get; set; }
        public decimal CostOnlyPerUnit { get; set; }
        public decimal CostValue { get; set; }
        public decimal Packsize { get; set; }
        public int Id { get; set; }
        public int FKProductDetails { get; set; }
        public Nullable<decimal> QtyPiece { get; set; }
        public Nullable<decimal> SellValue { get; set; }
        public int FKProduct { get; set; }
    }
}
