//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_CUSTOMER_MAST
    {
        public int ROWID { get; set; }
        public int CUSTOMER_NO { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_BRANCH { get; set; }
        public string CUSTOMER_TAXID { get; set; }
        public string CUSTOMER_ADDRESS { get; set; }
        public string CUSTOMER_PROVINCE { get; set; }
        public string CUSTOMER_POSTNO { get; set; }
        public string CUSTOMER_PHONE { get; set; }
        public string CUSTOMER_FAX { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string USER_ID { get; set; }
    }
}
