//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_LOCSTK
    {
        public int ROWID { get; set; }
        public string WH_NO { get; set; }
        public string LOCATION_TYPE { get; set; }
        public string LOCATION_NO { get; set; }
        public string ITEM_STATUS { get; set; }
        public string DOOR_NO { get; set; }
        public string PRODUCT_NO { get; set; }
        public string WH_BARCODE { get; set; }
        public Nullable<float> QTY { get; set; }
        public Nullable<float> BOOK_QTY { get; set; }
        public string UNIT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<float> PACK_SIZE { get; set; }
        public Nullable<float> QTY_PIECE { get; set; }
    }
}
