//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class WH_PRODUCT_MAST_HD_DELETE
    {
        public int ROWID { get; set; }
        public int HD_ROWID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public int BRAND_NO { get; set; }
        public int GROUP_NO { get; set; }
        public decimal COST_PIECE { get; set; }
        public string DOOR_NO { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string USER_ID { get; set; }
        public string SKU_KEY { get; set; }
        public System.DateTime DELETE_DATE { get; set; }
        public int DELETE_USER { get; set; }
    }
}
